### Obtener todos los contactos (Local)
GET http://localhost:8080/contacts

### Obtener un contacto individual por ID (Local)
GET http://localhost:8080/contacts/6aa043e47801582ca37ef105

### Obtener todos los contactos (Render)
GET https://cse-341-project1-xa4s.onrender.com/contacts

### Obtener un contacto por ID (Render)
GET https://cse-341-project1-xa4s.onrender.com/contacts/6aa043e47801582ca37ef105